# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    working_directory: ~/Rest_api_javascript_axios/Test-Framework
    steps:
      - checkout:
          path: ~/Rest_api_javascript_axios
          cache-path: node_modules
      - run: npm install
      - run: npm test